---
# tasks file for server
- name: Install 
  ansible.builtin.yum:
    name: 
      - policycoreutils 
      - perl
      - postfix
    state: present
- name: Enable service postfix, and not touch the state
  ansible.builtin.service:
    name: postfix
    enabled: yes

- name: Start service postfix, if not started
  ansible.builtin.service:
    name: postfix
    state: started
- name: Run shell curl configuration
  ansible.builtin.shell: sudo curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh | sudo bash  
- name: Run shell dnf install -y gitlab-ee 
  ansible.builtin.shell: sudo EXTERNAL_URL="https://server.example.com" dnf install -y gitlab-ee
- name: Disable port 80
  ansible.builtin.copy:
    src: files/gitlab.rb
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: '0600'
- name: Run shell gitlab-ctl reconfigure
  ansible.builtin.shell: sudo gitlab-ctl reconfigure
- name: Disable port 80
  ansible.builtin.copy:
    src: files/gitlab-rest
    dest: /tmp/gitlab-rest
    owner: root
    group: root
    mode: '0600'
- name: Run shell reset password
  ansible.builtin.shell: sudo gitlab-rake "gitlab:password:reset[root]" < /tmp/gitlab-rest


- name: Install repositorio zabbix
  ansible.builtin.yum: 
    name: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-latest.el9.noarch.rpm
    state: present
    disable_gpg_check: true
- name: Install one specific version of zabbix-server
  ansible.builtin.yum:
    name: 
      - zabbix-server-mysql 
      - zabbix-web-mysql 
      - zabbix-apache-conf 
      - zabbix-sql-scripts 
      - zabbix-selinux-policy 
      - zabbix-agent 
      - mysql
      - mysql-server
    state: present
- name: Enable service mysql-server, and not touch the state
  ansible.builtin.service:
    name: mysqld
    enabled: yes


- name: Start service mysql-server, if not started
  ansible.builtin.service:
    name: mysqld
    state: started
- name: Run shell mysql configuration
  ansible.builtin.shell: |
    mysql -u root -e "create database zabbix character set utf8mb4 collate utf8mb4_bin;"
    mysql -u root -e "create user zabbix@localhost identified by 'password';"
    mysql -u root -e "grant all privileges on zabbix.* to zabbix@localhost;"
    mysql -u root -e "set global log_bin_trust_function_creators = 1;"
  
- name: Run shell mysql configuration
  ansible.builtin.shell: zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -ppassword zabbix 
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/zabbix.conf.php
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: apache
    group: apache
    mode: '0600'
- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_server.conf 
    line: DBPassword=password
    insertafter: '^#DBPassword'
    
- name: Enable service, and not touch the state
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - zabbix-server 
    - zabbix-agent 
    - httpd 
    - php-fpm


- name: Start service zabbix-agent, if not started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  loop:
    - zabbix-server 
    - zabbix-agent 
    - httpd 
    - php-fpm

- name: Install packages
  ansible.builtin.yum:
    name: 
      - ansible-builder.noarch
      - ansible-rulebook.noarch
      - ansible-lint.noarch
      - socat.x86_64
      - wireshark.x86_64
      - tcpdump.x86_64
      - ansible-navigator
      - molecule
    state: present
